### ISSUE TITLE
Issue using anaconda with seaborn

### ISSUE THREAD

**Issue by ClimateYukon** [ua-snap/alfresco_postprocessing#5]
In plot.py, seaborn is import first in the main section and then again.
That cause a crash with anaconda using ipython for debugging as it gives me a no Display issue.
Simple fix would be to insert that before importing seaborn in the global scope.
```
import matplotlib as mpl
mpl.use('Agg')
```
Not sure why the conda package don't like that but it seems to be the issue.

**Comment by EarthScientist** [comment]
@julienschroder please have a look at the `fix_plot_imports` branch and see if the problem you describe with conda is solved.  I dont use conda and dont have a working version of that environment to test in, but I made the suggested change in your ticket above.

**Comment by EarthScientist** [comment]
closed with #6
